### ISSUE TITLE
wordpress puppeteer

### ISSUE THREAD

**Issue by ankitsmart63** [aduth/gutenberg.run#12]
i read in wordpress docs than gutenberg uses puppeteer, i also want to use puppeteer in wordpress but unable to find a way to use it,can you tell me the way or link to place where step by step procedure is held to use puppeteer on my wordpress site.
thanks

**Comment by aduth** [comment]
Hi there 👋  This project isn't officially affiliated with WordPress or Gutenberg, and it doesn't use Puppeteer.

You might have more luck at the WordPress Gutenberg project:

- https://github.com/WordPress/gutenberg
- https://developer.wordpress.org/block-editor/

Specifically, you might want to check on `@wordpress/scripts`, and its included features for using Puppeteer to do end-to-end testing:

- https://developer.wordpress.org/block-editor/packages/packages-scripts/
- https://www.liip.ch/en/blog/how-to-test-your-gutenberg-blocks
