### ISSUE TITLE
Build not working on IE

### ISSUE THREAD

**Issue by tellthemachines** [aduth/gutenberg.run#2]
Trying to build a PR preview on IE11/Windows 10 fails with `Object doesn't support property or method 'fetch'` in the console. IE doesn't support `window.fetch`; something like https://github.com/axios/axios could be used instead.

**Comment by aduth** [comment]
Thanks for the report! It's definitely intended that gutenberg.run should support Internet Explorer.

Some specific notes:

Issue is here:

https://github.com/aduth/gutenberg.run/blob/e38bff8f03e460488adf1db0a959462d53f9d815/web/static/run.js#L171

And:

https://github.com/aduth/gutenberg.run/blob/e38bff8f03e460488adf1db0a959462d53f9d815/web/static/run.js#L181

I'd probably prefer to use a polyfill than an external library, ideally one which doesn't add any bytes for an environment where it's not needed.

Perhaps one of:

- [polyfill.io](https://polyfill.io/v3/)
- A strategy similar to that in WordPress ([source](https://github.com/WordPress/wordpress-develop/blob/e8c854d2ce27e570da905d5b421047f357b5a289/src/wp-includes/script-loader.php#L120-L123)) using a [combination of a condition and `document.write`](https://github.com/WordPress/wordpress-develop/blob/e8c854d2ce27e570da905d5b421047f357b5a289/src/wp-includes/script-loader.php#L198-L207)

**Comment by aduth** [comment]
Implemented compatibility as a combination of f2368ca3e970ea25b3f4b19e925a178746fb4092 and f47797c7b2439ca1e495994a81f34e744c6dbac3.
