### ISSUE TITLE
Loads incredibly long or does not work at all

### ISSUE THREAD

**Issue by SchneiderSam** [aduth/gutenberg.run#4]
Loads incredibly long or does not work at all

Tested with 19344 PR: https://www.screencast.com/t/6njLbhpbM

Waiting for 10min and still loading.

**Comment by aduth** [comment]
Hi @SchneiderSam , I just restarted the server about the same time you created this issue, which may correspond to the issue you were experiencing. Can you give it another try now?

One thing I observed was that the "clean-up" process was missing quite a few old sites, which may have resulted in a lot of memory being dedicated to sites which should have been deleted. I manually removed those, which should hopefully help as a short-term solution, but the underlying bug will need to be addressed for this to not be a problem in the future.
