### ISSUE TITLE
Again very slow or it does not load at all

### ISSUE THREAD

**Issue by SchneiderSam** [aduth/gutenberg.run#6]
I just want to give a short feedback: the loading time is again very slow or it does not load at all. I have simply tried this with http://gutenberg.run/21121. But the same behaviour as back then... https://github.com/aduth/gutenberg.run/issues/4

Thx for this feature!

**Comment by aduth** [comment]
Hm, on first glance, it appears to load quite quickly for me. The initial build will take some few minutes, which has always been the case (and likely will always be). Were you observing absurdly long build times?

At least on checking the server processes, there's not the problem that led to #4. In the earlier problems, the Docker containers were not being cleaned up, which meant there were dozens of sites all running in the (very resource-limited) server. The number of containers active on the server at this current moment looks reasonable to me.

**Comment by SchneiderSam** [comment]
Hm, no idea, I've been waiting for 5 minutes and nothing is happening :-S

**Comment by SchneiderSam** [comment]
After your answer tested again, and now it works... 

hm..

**Comment by aduth** [comment]
I don't see any errors in my [Sentry](https://sentry.io/) dashboard either. Maybe there was some issue that the connection between your browser and the server? My expectation is that this too would be handled gracefully ([source](https://github.com/aduth/gutenberg.run/blob/c62f7545107a3ff4bf70ea401ca0d7aa7a0edf9d/web/static/run.js#L149-L157)), but I may be missing something. There's [some weird (and browser-specific) behavior](https://stackoverflow.com/a/27840379) in how these sorts of [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) handle disconnections.

I don't have much actionable here. If it happens again, could you check your browser's [DevTools](https://developers.google.com/web/tools/chrome-devtools) to see if any errors are logged? Or the [network tab](https://developers.google.com/web/tools/chrome-devtools/network) to see if there's any errors in the connections.
