### ISSUE TITLE
When failing to load a PR, provide error message

### ISSUE THREAD

**Issue by enriquesanchez** [aduth/gutenberg.run#7]
Today I was trying to test http://gutenberg.run/20008. You'll notice that the PR fails to load, and I assume that is due to the fact that the PR has already been merged.

In cases like this, it'd be great if a reason for failure was provided.

"This pull request cannot be loaded becase it has already been merged"... or something like that.

**Comment by aduth** [comment]
Can you give it another try? There were some issues the last few days with the server running out of storage space. As I understand the implementation, it shouldn't be an issue to build an environment for a merged pull request, as it's simply building at a specific commit (the merge commit of the pull request) which, as best I can tell, is still valid after merge.

Will proactively close issue, but if it's still a problem, let's reopen.
