### ISSUE TITLE
Provide a way to run master on gutenberg.run

### ISSUE THREAD

**Issue by enriquesanchez** [aduth/gutenberg.run#8]
This project has been incredibly helpful and useful for a lot of folks who can't or don't know how to run a Gutenberg dev environment but still want to help test PRs.

I think it'd be great if we take it a step further and allow to run current master. [Sometimes a PR has already been merged](https://github.com/aduth/gutenberg.run/issues/7), or someone just wants to tests the most recent development.

I'm now sure if this will be technically possible, but I think it'd be really useful and worth exploring.

**Comment by aduth** [comment]
Yes, it's very technically possible, and in-fact could be done today if someone manually crafted requests to the servers in a way which mimics how it's done for any other pull request. The server merely creates an environment based on a certain commit hash, which can be `master`. It's just not exposed to the UI currently in a way to do so conveniently.

I'd definitely like to explore this, as well as a few other possible "quick start" options (e.g. latest plugin version, older plugin versions, "popular" pull requests, etc). The landing page needs some love 😄

**Comment by aduth** [comment]
Pretty low-tech solution right now, but you can pass a branch as a query parameter:

https://gutenberg.run/?branch=master

Ref 8d98e3e2b6ac14571e882f4d0225473686081ae5
